#数据库连接
spring: 
    thymeleaf: 
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        mode: LEGACYHTML5
        servlet:
            content-type: text/html
    datasource:
        url: jdbc:mysql://localhost:3306/park?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
        username: root
        password: chen00.
        driver-class-name: com.mysql.cj.jdbc.Driver

#服务器端口
server: 
  port: 90
  